# Generated by Django 4.2.5 on 2023-10-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('National_ID', models.IntegerField()),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
