# Generated by Django 4.2.5 on 2023-10-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Registration_No',
            field=models.CharField(default=True, max_length=25),
        ),
    ]
